### ISSUE TITLE
multi-gpu training hangs

### ISSUE THREAD

**Issue by ajtao** [CompVis/taming-transformers#12]
Hmm, training with `--gpus 0,` works fine but training with `--gpus 0,1` hangs right at `initializing ddp ...`

**Comment by ajtao** [comment]
Hmm, maybe this is related: https://github.com/PyTorchLightning/pytorch-lightning/issues/4612

**Comment by MicPie** [comment]
I seem to have the same problem. How did you solved it?

**Comment by ajtao** [comment]
In our environment we were setting NODE_RANK. pytorch lightning didn't like this to be set, so that fixed it for us.

**Comment by ajtao** [comment]
We had an environment variable called NODE_RANK set. We unset it, and it fixed things. Outside of that, i can't help you.
