### ISSUE TITLE
NCCL error

### ISSUE THREAD

**Issue by alex-pv01** [CompVis/taming-transformers#227]
Hi, I am trying to train a vqgan on a custom dataset. I followed the instructions on the read.me file. However, as I run the command

`python main.py --base configs/custom_vqgan.yaml -t True --gpus 0,1`

I get the following error:

![image](https://github.com/CompVis/taming-transformers/assets/131586706/7329a053-22ba-4dc1-b352-39bcaff2c6a4)

Take into account that I want to run this in a distributed server that has several RTX 3090.

Any suggestion on how to solve this?

Thx

**Comment by alex-pv01** [comment]
I fixed it by reinstalling a different version of torch with command:
`pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by alex-pv01** [comment]
I fixed it by reinstalling a different version of torch with command:
`pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by wwqy** [comment]
> I fixed it by reinstalling a different version of torch with command: `pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

I tried this way, but cannot solve this bug. Is there any other methods?

**Comment by PeiqinSun** [comment]
any solution?

**Comment by xuezhongcailian** [comment]
同问
