### ISSUE TITLE
gpu training hangs

### ISSUE THREAD

**Issue by shyakocat** [CompVis/taming-transformers#235]
[Related Issue](https://github.com/CompVis/taming-transformers/issues/12)

training with `--gpus 0,`  `--gpus 0,1` hangs at initializing ddp ...

I've tried, change `ddp` to `dp`, change `nccl` to `gloo`, upgrade lightning or torch version... still not work.

(only cpu works)

**Comment by hllion** [comment]
@shyakocat  I encountered the same issue, have you resolved it?

**Comment by froestiago** [comment]
try running `export NCCL_P2P_DISABLE=1` before running the script
it worked for me

**Comment by fee-mugre** [comment]
> try running `export NCCL_P2P_DISABLE=1` before running the script it worked for me

This seem to solve the situation with only --gpu 0, works but --gpus 0,1 not work.

**Comment by fee-mugre** [comment]
> > try running `export NCCL_P2P_DISABLE=1` before running the script it worked for me
> 
> This seem to solve the situation with only --gpu 0, works but --gpus 0,1 not work.

I updata the torch version then it works.
